# Generated by Django 5.1.3 on 2026-01-09 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("note", "Note"),
                            ("prompt", "Prompt"),
                            ("answer", "Answer"),
                            ("artifact", "Artifact"),
                            ("mixed", "Mixed"),
                        ],
                        default="note",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1)),
                ("draft_delta", models.JSONField(blank=True, default=dict)),
                ("draft_html", models.TextField(blank=True, default="")),
                ("draft_text", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("archived", "Archived")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("pinned", models.BooleanField(default=False)),
                ("last_opened_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": (
                    "-pinned",
                    "-last_opened_at",
                    "-updated_at",
                    "-created_at",
                ),
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="EntryRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rev_no", models.PositiveIntegerField(default=1)),
                ("delta", models.JSONField(blank=True, default=dict)),
                ("html", models.TextField(blank=True, default="")),
                ("text", models.TextField(blank=True, default="")),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="notes_app.entry",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.AddField(
            model_name="entry",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="notes_app.section",
            ),
        ),
        migrations.CreateModel(
            name="SectionSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("snapshot", "Snapshot"), ("release", "Release")],
                        default="snapshot",
                        max_length=20,
                    ),
                ),
                ("rev_no", models.PositiveIntegerField(default=1)),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="notes_app.section",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.AddField(
            model_name="section",
            name="release_snapshot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="notes_app.sectionsnapshot",
            ),
        ),
        migrations.CreateModel(
            name="SectionSnapshotItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="notes_app.entry",
                    ),
                ),
                (
                    "entry_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="notes_app.entryrevision",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="notes_app.sectionsnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="notes_app.project",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
        migrations.AddField(
            model_name="section",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="notes_app.topic",
            ),
        ),
        migrations.AddIndex(
            model_name="entryrevision",
            index=models.Index(
                fields=["entry", "rev_no"], name="notes_app_e_entry_i_b1cb12_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="entry",
            unique_together={("section", "order")},
        ),
        migrations.AddIndex(
            model_name="sectionsnapshot",
            index=models.Index(
                fields=["section", "rev_no"], name="notes_app_s_section_b79603_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sectionsnapshotitem",
            unique_together={("snapshot", "order")},
        ),
        migrations.AlterUniqueTogether(
            name="topic",
            unique_together={("project", "order")},
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("topic", "order")},
        ),
    ]
