# Generated by Django 5.1.3 on 2026-01-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="structure",
            field=models.CharField(
                choices=[
                    ("topics", "Topics → Sections → Entries"),
                    ("sections", "Sections → Entries"),
                    ("entries", "Entries only"),
                ],
                db_index=True,
                default="sections",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="is_system",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="topic",
            name="is_system",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("done", "Done")],
                default="active",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="order",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="topic",
            name="order",
            field=models.IntegerField(default=1),
        ),
    ]
